project:
  type: website
  output-dir: docs

website:
  title: "Davide Tornotti"
  navbar:
    left:
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



